const catalog: Record<string,{name:string;type:string;description:string}>={
 'nad-plus':{name:'NAD+',type:'Research Material',description:'A research-use-only laboratory material. Review the product documentation and specifications before purchase.'},
 'ghk-cu':{name:'GHK-Cu',type:'Research Material',description:'A research-use-only laboratory material. Review the product documentation and specifications before purchase.'},
 'bpc-157':{name:'BPC-157',type:'Research Material',description:'A research-use-only laboratory material. Review the product documentation and specifications before purchase.'},
 'tb-500':{name:'TB-500',type:'Research Material',description:'A research-use-only laboratory material. Review the product documentation and specifications before purchase.'},
 'cjc-ipamorelin':{name:'CJC / Ipamorelin',type:'Research Material',description:'A research-use-only laboratory material. Review the product documentation and specifications before purchase.'},
 'bac-water':{name:'BAC Water',type:'Laboratory Supply',description:'A laboratory supply presented for research applications. Review the applicable documentation before purchase.'}
}
export default async function Product({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=catalog[slug]||{name:'Research Material',type:'Research Material',description:'Product information unavailable.'};return <><div className="topbar">RESEARCH USE ONLY <span>•</span> NOT FOR HUMAN OR VETERINARY USE</div><header className="site-header wrap"><a className="brand" href="/">VOIÉLA</a><nav className="links"><a href="/shop">Shop</a><a href="/about">About</a><a href="/faq">FAQ</a><a href="/checkout">Cart</a></nav></header><main className="wrap product-page"><div className="product-detail"><div className="product-visual visual-2 detail-visual"><span>VOIÉLA</span><small>RUO</small></div><div className="product-info"><div className="eyebrow">{p.type}</div><h1>{p.name}</h1><p className="lead">{p.description}</p><div className="product-rule"/><p className="ruo"><strong>RESEARCH USE ONLY</strong><br/>Not for human or veterinary use. No dosing, administration, or personal-use guidance is provided.</p><button className="button" disabled>Purchase — Coming soon</button></div></div><div className="final-notice"><strong>IMPORTANT</strong><p>This listing is for laboratory research purposes only. It is not a drug, supplement, food, treatment, or medical product, and is not intended to diagnose, treat, cure, or prevent any disease.</p></div></main></>}
